<?php

namespace Oyst\Service;

class Configuration
{
    const ONE_CLICK_FEATURE_STATE = 'OYST_ONE_CLICK_FEATURE_STATE';
    const ONE_CLICK_FEATURE_ENABLE = 1;
    const ONE_CLICK_FEATURE_DISABLE = 0;
    const ONE_CLICK_CARRIER = 'OYST_ONE_CLICK_CARRIER';

    const API_ENV = 'FC_OYST_API_ENV';
    const API_ENV_PROD = 'prod';
    const API_ENV_PREPROD = 'preprod';
    const API_KEY_PROD = 'FC_OYST_API_PROD_KEY';
    const API_KEY_PREPROD = 'FC_OYST_API_PREPROD_KEY';
    const API_ENDPOINT_PROD = 'OYST_API_PROD_ENDPOINT';
    const API_ENDPOINT_PREPROD = 'OYST_API_PREPROD_ENDPOINT';

    const CATALOG_EXPORT_STATE = 'OYST_CATALOG_EXPORT_STATE';
    const CATALOG_EXPORT_RUNNING = 1;
    const CATALOG_EXPORT_DONE = 0;

    const DISPLAY_ADMIN_INFO_STATE = 'OYST_DISPLAY_ADMIN_INFO_STATE';
    const DISPLAY_ADMIN_INFO_ENABLE = 1;
    const DISPLAY_ADMIN_INFO_DISABLE = 0;

    const REQUESTED_CATALOG_DATE = 'OYST_REQUESTED_CATALOG_DATE';
}
